class Solution {

        class Node {
                char left, right;
                        int pre, suf, best, len;

                                Node(char c) {
                                            left = right = c;
                                                        pre = suf = best = len = 1;
                                                                }
                                                                    }

                                                                        Node[] tree;
                                                                            char[] s;

                                                                                public int[] longestRepeating(String str, String queryCharacters,
                                                                                                                  int[] queryIndices) {

                                                                                                                          s = str.toCharArray();
                                                                                                                                  int n = s.length;

                                                                                                                                          tree = new Node[4 * n];
                                                                                                                                                  build(1, 0, n - 1);

                                                                                                                                                          int[] ans = new int[queryIndices.length];

                                                                                                                                                                  for (int i = 0; i < queryIndices.length; i++) {
                                                                                                                                                                              int index = queryIndices[i];

                                                                                                                                                                                          s[index] = queryCharacters.charAt(i);

                                                                                                                                                                                                      update(1, 0, n - 1, index);

                                                                                                                                                                                                                  ans[i] = tree[1].best;
                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                  return ans;
                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                          void build(int node, int l, int r) {
                                                                                                                                                                                                                                                  if (l == r) {
                                                                                                                                                                                                                                                              tree[node] = new Node(s[l]);
                                                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                          int mid = (l + r) / 2;

                                                                                                                                                                                                                                                                                                  build(node * 2, l, mid);
                                                                                                                                                                                                                                                                                                          build(node * 2 + 1, mid + 1, r);

                                                                                                                                                                                                                                                                                                                  tree[node] = merge(tree[node * 2], tree[node * 2 + 1]);
                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                          void update(int node, int l, int r, int index) {
                                                                                                                                                                                                                                                                                                                                  if (l == r) {
                                                                                                                                                                                                                                                                                                                                              tree[node] = new Node(s[index]);
                                                                                                                                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                          int mid = (l + r) / 2;

                                                                                                                                                                                                                                                                                                                                                                                  if (index <= mid)
                                                                                                                                                                                                                                                                                                                                                                                              update(node * 2, l, mid, index);
                                                                                                                                                                                                                                                                                                                                                                                                      else
                                                                                                                                                                                                                                                                                                                                                                                                                  update(node * 2 + 1, mid + 1, r, index);

                                                                                                                                                                                                                                                                                                                                                                                                                          tree[node] = merge(tree[node * 2], tree[node * 2 + 1]);
                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                  Node merge(Node a, Node b) {
                                                                                                                                                                                                                                                                                                                                                                                                                                          Node res = new Node(a.left);

                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.len = a.len + b.len;
                                                                                                                                                                                                                                                                                                                                                                                                                                                          res.left = a.left;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.right = b.right;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          res.pre = a.pre;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.suf = b.suf;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          res.best = Math.max(a.best, b.best);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (a.right == b.left) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              res.best = Math.max(res.best, a.suf + b.pre);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (a.pre == a.len)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          res.pre = a.len + b.pre;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (b.suf == b.len)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      res.suf = b.len + a.suf;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return res;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
